---
- name: Install Docker and Docker Compose on GCP VM
  hosts: gcp-vm
  become: true
  tasks:
    - name: Update apt repository cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: latest

    - name: Add user to the Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Download Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.25.0/docker-compose-linux-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: "0755"

    - name: Verify Docker Compose installation
      shell: docker-compose --version
      register: docker_compose_version

    - name: Print Docker Compose version
      debug:
        msg: "{{ docker_compose_version.stdout }}"
